### ISSUE TITLE
[US] As a developer, I want to know how to use RabbitMQ in my services

### ISSUE THREAD

**Issue by blyndusk** [blyndusk/image-resizer#4]
## Tasks:
- [ ] what is RabbitMQ ?
- [ ] what the purpose of RabbitMQ ?
- [ ] How to use RabbitMQ with my services ?
