### ISSUE TITLE
[US] As a developer, I want to have a User entity + CRUD

### ISSUE THREAD

**Issue by alexandre-delaloy** [blyndusk/image-resizer#8]
## Tasks:
- [ ] create User model
- [ ] create User controller
- [ ] create User middleware
