### ISSUE TITLE
[US] As a udeveloper, I want to have an Avatar entity + CRUD

### ISSUE THREAD

**Issue by blyndusk** [blyndusk/image-resizer#9]
## Tasks:
- [ ] create Avatar model
- [ ] create Avatar controller
- [ ] create Avatar middleware
